import doctor1 from '../../assets/doctor1.png'
import doctor2 from '../../assets/doctor2.png'
import doctor3 from '../../assets/doctor3.png'


export const DummyDoctors=[
    {
        id: 1,
        name: 'Dr. Medhat El Shazly',
        specialty: 'Cardiologist',
        position: 'Head of Cardiology Department – Cairo Heart Center',
        rating: 4.8,
        reviews: 145,
        image: doctor1,
        available: true,
        services: 'Heart Checkup, ECG & ECHO Tests, Blood Pressure Management, Cardiac Surgery Consultation',
        appointments: [
            { day: 'Sunday', time: '9:00 AM - 12:00 PM' },
            { day: 'Tuesday', time: '1:00 PM - 4:00 PM' },
            { day: 'Thursday', time: '10:00 AM - 1:00 PM' },
        ],
    },
    {
        id: 2,
        name: 'Dr. Khaled Ali',
        specialty: 'Cardiologist',
        position: 'Senior Consultant – Brain & Nerve Disorders',
        rating: 4.6,
        reviews: 97,
        image: doctor2,
        available: true,
        services: 'Migraine Treatment, Epilepsy Diagnosis, Sleep Disorder Therapy, Stroke Rehabilitation',
        appointments: [
            { day: 'Monday', time: '10:00 AM - 2:00 PM' },
            { day: 'Wednesday', time: '3:00 PM - 6:00 PM' },
        ],
    },
    {
        id: 3,
        name: 'Dr. Ahmed Mohamed',
        specialty: 'Child Specialist',
        position: 'Pediatric Consultant – Nile Hospital',
        rating: 4.7,
        reviews: 88,
        image: doctor3,
        available: true,
        services: 'Child Growth Checkup, Vaccinations, Nutritional Counseling, Pediatric Allergy Treatment',
        appointments: [
            { day: 'Sunday', time: '2:00 PM - 5:00 PM' },
            { day: 'Tuesday', time: '9:00 AM - 12:00 PM' },
        ],
    },
    {
        id: 4,
        name: 'Dr. Mona Hassan',
        specialty: 'Dermatologist',
        position: 'Consultant Dermatologist – Derma Care Clinic',
        rating: 4.9,
        reviews: 123,
        image: doctor1,
        available: true,
        services: 'Skin Care Consultation, Laser Treatments, Acne & Scar Removal, Anti-Aging Therapy',
        appointments: [
            { day: 'Monday', time: '9:00 AM - 12:00 PM' },
            { day: 'Thursday', time: '2:00 PM - 5:00 PM' },
        ],
    },
    {
        id: 5,
        name: 'Dr. Eman Saleh',
        specialty: 'Dentist',
        position: 'Cosmetic Dentist – Smile Studio',
        rating: 4.8,
        reviews: 110,
        image: doctor2,
        available: false,
        services: 'Teeth Whitening, Braces & Aligners, Dental Implants, Regular Checkups',
        appointments: [
            { day: 'Sunday', time: '11:00 AM - 3:00 PM' },
            { day: 'Wednesday', time: '9:00 AM - 12:00 PM' },
        ],
    },
    {
        id: 6,
        name: 'Dr. Youssef Ibrahim',
        specialty: 'Orthopedic Surgeon',
        position: 'Consultant Orthopedic Surgeon – MedCare Hospital',
        rating: 4.7,
        reviews: 98,
        image: doctor3,
        available: true,
        services: 'Bone Fracture Treatment, Joint Replacement, Sports Injury Care, Spine Surgery',
        appointments: [
            { day: 'Monday', time: '10:00 AM - 2:00 PM' },
            { day: 'Thursday', time: '3:00 PM - 6:00 PM' },
        ],
    },
    {
        id: 7,
        name: 'Dr. Laila Tarek',
        specialty: 'Gynecologist',
        position: 'Specialist in Women’s Health – Family Clinic',
        rating: 4.9,
        reviews: 156,
        image: doctor1,
        available: true,
        services: 'Pregnancy Follow-up, Ultrasound Scans, Fertility Counseling, Hormonal Disorder Treatment',
        appointments: [
            { day: 'Sunday', time: '10:00 AM - 1:00 PM' },
            { day: 'Wednesday', time: '2:00 PM - 5:00 PM' },
        ],
    },
    {
        id: 8,
        name: 'Dr. Omar Nabil',
        specialty: 'ENT Specialist',
        position: 'Consultant – Ear, Nose & Throat Department, City Hospital',
        rating: 4.6,
        reviews: 85,
        image: doctor2,
        available: false,
        services: 'Hearing Tests, Sinus Treatment, Tonsil Surgery, Voice & Throat Care',
        appointments: [
            { day: 'Tuesday', time: '9:00 AM - 12:00 PM' },
            { day: 'Thursday', time: '1:00 PM - 4:00 PM' },
        ],
    },
    {
        id: 9,
        name: 'Dr. Sara Mahmoud',
        specialty: 'Ophthalmologist',
        position: 'Eye Specialist – Vision Care Center',
        rating: 4.8,
        reviews: 85,
        image: doctor3,
        available: true,
        services: 'Eye Examination, Laser Vision Correction, Cataract Surgery, Children’s Eye Care',
        appointments: [
            { day: 'Sunday', time: '9:00 AM - 1:00 PM' },
            { day: 'Tuesday', time: '2:00 PM - 5:00 PM' },
        ],
    },
    {
        id: 10,
        name: 'Dr. Tamer Adel',
        specialty: 'Psychiatrist',
        position: 'Consultant Psychiatrist – Mind & Wellness Clinic',
        rating: 4.9,
        reviews: 140,
        image: doctor1,
        available: true,
        services: 'Anxiety & Depression Therapy, Family Counseling, Behavioral Therapy, Child Psychiatry',
        appointments: [
            { day: 'Monday', time: '10:00 AM - 2:00 PM' },
            { day: 'Thursday', time: '3:00 PM - 6:00 PM' },
        ],
    },
]